spring:
  redis:
    host: 127.0.0.1
    database: 5
    port: 6379
    password: ****
    jedis:
      pool:
        max-active: 50
        max-idle: 10
        min-idle: 0
        max-wait: 30000ms
  # 数据源
  datasource:
    name: ****
    # 数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 用户名
    username: ****
    # 密码
    password: ****
    url: jdbc:mysql://localhost:3306/****?useSSL=false&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      #初始化大小，最小，最大
      initial-size: 1
      min-idle: 1
      #最大连接等待超时时间
      max-wait: 60000
      #配置多久进行一次检测需要关闭的连接时间（毫秒）
      time-between-eviction-runs-millis: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      pool-prepared-statements: true
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      min-evictable-idle-time-millis: 300000
      #重连配置
      validation-query: select 1
      test-on-return: false
      test-on-borrow: false
      test-while-idle: true
      filter:
        stat:
          db-type: mysql
          slow-sql-millis: 3000
          log-slow-sql: true
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat,wall,slf4j
      use-local-session-state: true
    initialization-mode: always
  jpa:
    # 日志sql
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
logging:
  file: ${env-config.project}.log
env-config:
  project: spring-redis
  session-expire: 2592000000 #30days