spring:
  redis:
    host: 127.0.0.1
    database: 5
    port: 6379
    password: Dayu1234
    jedis:
      pool:
        max-active: 50
        max-idle: 10
        min-idle: 0
        max-wait: 30000ms
logging:
  file: ${env-config.project}.log
env-config:
  project: spring-redis